#!/bin/bash

UTILS_DIR=$(cd "$(dirname "$0")"; pwd)/utils
OCI=127.0.0.1
ONOS_NETCFG_IMG=maven:3.6.3-jdk-11

docker run -it --rm \
  --name onos-app \
  --network host \
  -v "$UTILS_DIR"/onos:/utils/onos \
  -v "$PWD":/workdir -w /workdir \
  $ONOS_NETCFG_IMG /utils/onos/onos-app $OCI "$@"
